### ISSUE TITLE
大佬能更新ucn_serialization.json和ucn_id.json这两个文件吗

### ISSUE THREAD

**Issue by hcy0317** [c2c3vsfac/Iridium-py-release#1]
要学习什么才能获取它们呀

**Comment by c2c3vsfac** [comment]
都是AbilityInvokeArgument.proto和CombatTypeArgument.proto里的枚举字段。先找有没有同名的proto，剩下的全靠猜。多次抓同一个包，如果部分不同最好，那些相同的地方就是对应的字段编号和字段类型；如果都一样，那只能按proto序列化的方式来试着反序列化。然后从所有proto中匹配字段编号和字段类型，再根据匹配到的文件名等来确认。

**Comment by hcy0317** [comment]
> 都是AbilityInvokeArgument.proto和CombatTypeArgument.proto里的枚举字段。先找有没有同名的proto，剩下的全靠猜。多次抓同一个包，如果部分不同最好，那些相同的地方就是对应的字段编号和字段类型；如果都一样，那只能按proto序列化的方式来试着反序列化。然后从所有proto中匹配字段编号和字段类型，再根据匹配到的文件名等来确认。

谢谢大佬，学废了
