### ISSUE TITLE
捕获无输出的问题

### ISSUE THREAD

**Issue by 2054686334** [c2c3vsfac/Iridium-py-release#2]
运行iridium-bruteforce.py后，不产生报错，debug后发现sniff函数正常工作并且可以获得抓包的数据，但正常运行时无论如何都没有任何输出，请问是否是我漏掉了一些步骤导致的？我没有对rsa的私钥进行修改，因为不知道要从哪里获取。

**Comment by c2c3vsfac** [comment]
应该是缺了一个sniffer_output文件夹的问题吧,你再试试。

**Comment by 2054686334** [comment]
> 应该是缺了一个sniffer_output文件夹的问题吧,你再试试。

感谢回复。
太晚了已经熄灯了，我明天尝试一下

**Comment by 2054686334** [comment]
我测，手机操作就是不方便，点到close了

**Comment by 2054686334** [comment]
创建文件夹试了一下，依旧无效，无任何输出

**Comment by c2c3vsfac** [comment]
你这无输出是指连send_req_time，xor_key都没有吗？如果是这样,我也不确定是什么问题。既然你说sniff工作正常，你把这两个函数改成这样再把输出发给我看看。
```python
def sniff_(iface_):
    sniff(iface=iface_, count=10, filter="udp port 22102||22101", prn=package_handle)

def package_handle(data):
    sniff_datas.append(bytes(data))
    print(bytes(data)[:80])
```

**Comment by 2054686334** [comment]
[main 2023-04-23T10:25:00.786Z] [SharedProcess] using utility process
[main 2023-04-23T10:25:00.867Z] update#setState idle
[main 2023-04-23T10:25:01.451Z] [UtilityProcess id: 1, type: extensionHost, pid: <none>]: creating new...
[main 2023-04-23T10:25:01.493Z] [UtilityProcess id: 1, type: extensionHost, pid: 16536]: successfully created
[main 2023-04-23T10:25:01.655Z] [UtilityProcess type: shared-process, pid: <none>]: creating new...
[main 2023-04-23T10:25:01.658Z] [UtilityProcess id: 1, type: fileWatcher, pid: <none>]: creating new...
[main 2023-04-23T10:25:01.697Z] [UtilityProcess type: shared-process, pid: 448]: successfully created
[main 2023-04-23T10:25:01.738Z] [UtilityProcess id: 1, type: fileWatcher, pid: 24688]: successfully created
[main 2023-04-23T10:25:30.876Z] update#setState checking for updates
[main 2023-04-23T10:25:30.982Z] update#setState idle
以上是截至开门之前的输出
[15828:0423/182701.063:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is
这一条是开门之后唯一的输出

**Comment by 2054686334** [comment]
[main 2023-04-23T10:25:00.786Z] [SharedProcess] using utility process
[main 2023-04-23T10:25:00.867Z] update#setState idle
[main 2023-04-23T10:25:01.451Z] [UtilityProcess id: 1, type: extensionHost, pid: ]: creating new...
[main 2023-04-23T10:25:01.493Z] [UtilityProcess id: 1, type: extensionHost, pid: 16536]: successfully created
[main 2023-04-23T10:25:01.655Z] [UtilityProcess type: shared-process, pid: ]: creating new...
[main 2023-04-23T10:25:01.658Z] [UtilityProcess id: 1, type: fileWatcher, pid: ]: creating new...
[main 2023-04-23T10:25:01.697Z] [UtilityProcess type: shared-process, pid: 448]: successfully created
[main 2023-04-23T10:25:01.738Z] [UtilityProcess id: 1, type: fileWatcher, pid: 24688]: successfully created
[main 2023-04-23T10:25:30.876Z] update#setState checking for updates
[main 2023-04-23T10:25:30.982Z] update#setState idle
以上是截至开门之前的输出
[15828:0423/182701.063:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is
这一条是开门之后唯一的输出

**Comment by 2054686334** [comment]
> [main 2023-04-23T10:25:00.786Z] [SharedProcess] using utility process [main 2023-04-23T10:25:00.867Z] update#setState idle [main 2023-04-23T10:25:01.451Z] [UtilityProcess id: 1, type: extensionHost, pid: ]: creating new... [main 2023-04-23T10:25:01.493Z] [UtilityProcess id: 1, type: extensionHost, pid: 16536]: successfully created [main 2023-04-23T10:25:01.655Z] [UtilityProcess type: shared-process, pid: ]: creating new... [main 2023-04-23T10:25:01.658Z] [UtilityProcess id: 1, type: fileWatcher, pid: ]: creating new... [main 2023-04-23T10:25:01.697Z] [UtilityProcess type: shared-process, pid: 448]: successfully created [main 2023-04-23T10:25:01.738Z] [UtilityProcess id: 1, type: fileWatcher, pid: 24688]: successfully created [main 2023-04-23T10:25:30.876Z] update#setState checking for updates [main 2023-04-23T10:25:30.982Z] update#setState idle 以上是截至开门之前的输出 [15828:0423/182701.063:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is 这一条是开门之后唯一的输出

重新启动了一次游戏，无任何多的输出

**Comment by c2c3vsfac** [comment]
如果你改了之后，还是什么输出都没有，那就是sniff函数都没有正常工作。你看看`config.json`里`\\Device\\NPF_{}`有没有变化，以及scapy库有安好吗。还有，不要用这debug模式运行，啥都看不出来。
```python
from scapy.all import sniff

def sniff_():
    sniff(count=10, prn=package_handle)

def package_handle(data):
    print(bytes(data)[:80])

sniff_()
```
你就用这段代码测试，单独作为一个文件就行，只要你的电脑有正在联网的应用，这段代码就不可能没有输出。你要是连这段代码都不能让它正常工作，那我也教不了你了。

**Comment by 2054686334** [comment]
> 如果你改了之后，还是什么输出都没有，那就是sniff函数都没有正常工作。你看看`config.json`里`\\Device\\NPF_{}`有没有变化，以及scapy库有安好吗。还有，不要用这debug模式运行，啥都看不出来。
> 
> ```python
> from scapy.all import sniff
> 
> def sniff_():
>     sniff(count=10, prn=package_handle)
> 
> def package_handle(data):
>     print(bytes(data)[:80])
> 
> sniff_()
> ```
> 
> 你就用这段代码测试，单独作为一个文件就行，只要你的电脑有正在联网的应用，这段代码就不可能没有输出。你要是连这段代码都不能让它正常工作，那我也教不了你了。

(base) PS D:\workspace\Iridium-py-release> python .\testtest.py
b'`U\xf9tK\x8c\x18\xc0M\xda-\xa9\x08\x00E\x00\x01\x1f\x07a\x00\x00\x80\x11\xb9\xa1\xc0\xa8{\xbb\xc0\xa8{\xbf\xfe"\x0f\xd0\x01\x0b\xb5\x9aA\x07\x01\x01\x00\x00\x00\x00\x00\xf9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'`U\xf9tK\x8c\x18\xc0M\xda-\xa9\x08\x00E\x00\x01\x1f\x07b\x00\x00\x80\x11\xb9\xa0\xc0\xa8{\xbb\xc0\xa8{\xbf\xfe"\x0f\xd0\x01\x0b\xb5\x99A\x08\x01\x01\x00\x00\x00\x00\x00\xf9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'`U\xf9tK\x8c\x18\xc0M\xda-\xa9\x08\x00E\x00\x01\x1f\x07c\x00\x00\x80\x11\xb9\x9f\xc0\xa8{\xbb\xc0\xa8{\xbf\xfe"\x0f\xd0\x01\x0b\xb5\x98A\t\x01\x01\x00\x00\x00\x00\x00\xf9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'`U\xf9tK\x8c\x18\xc0M\xda-\xa9\x08\x00E\x00\x01\x1f\x07d\x00\x00\x80\x11\xb9\x9e\xc0\xa8{\xbb\xc0\xa8{\xbf\xfe"\x0f\xd0\x01\x0b\xb5\x97A\n\x01\x01\x00\x00\x00\x00\x00\xf9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'`U\xf9tK\x8c\x18\xc0M\xda-\xa9\x08\x00E\x00\x01\x1f\x07e\x00\x00\x80\x11\xb9\x9d\xc0\xa8{\xbb\xc0\xa8{\xbf\xfe"\x0f\xd0\x01\x0b\xb5\x96A\x0b\x01\x01\x00\x00\x00\x00\x00\xf9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'`U\xf9tK\x8c\x18\xc0M\xda-\xa9\x08\x00E\x00\x01\x1f\x07f\x00\x00\x80\x11\xb9\x9c\xc0\xa8{\xbb\xc0\xa8{\xbf\xfe"\x0f\xd0\x01\x0b\xb5\x95A\x0c\x01\x01\x00\x00\x00\x00\x00\xf9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'`U\xf9tK\x8c\x18\xc0M\xda-\xa9\x08\x00E\x00\x01\x1f\x07g\x00\x00\x80\x11\xb9\x9b\xc0\xa8{\xbb\xc0\xa8{\xbf\xfe"\x0f\xd0\x01\x0b\xb5\x94A\r\x01\x01\x00\x00\x00\x00\x00\xf9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'`U\xf9tK\x8c\x18\xc0M\xda-\xa9\x08\x00E\x00\x01\x1f\x07h\x00\x00\x80\x11\xb9\x9a\xc0\xa8{\xbb\xc0\xa8{\xbf\xfe"\x0f\xd0\x01\x0b\xb5\x93A\x0e\x01\x01\x00\x00\x00\x00\x00\xf9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'`U\xf9tK\x8c\x18\xc0M\xda-\xa9\x08\x00E\x00\x01\x1f\x07i\x00\x00\x80\x11\xb9\x99\xc0\xa8{\xbb\xc0\xa8{\xbf\xfe"\x0f\xd0\x01\x0b\xb5\x92A\x0f\x01\x01\x00\x00\x00\x00\x00\xf9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'`U\xf9tK\x8c\x18\xc0M\xda-\xa9\x08\x00E\x00\x01\x1f\x07j\x00\x00\x80\x11\xb9\x98\xc0\xa8{\xbb\xc0\xa8{\xbf\xfe"\x0f\xd0\x01\x0b\xb5\xa1A\x00\x01\x01\x00\x00\x00\x00\x00\xf9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
输出如上，我之前也测试过了sniff是正常工作的

**Comment by 2054686334** [comment]
实在是解决不了了，望大佬指点，折腾了两天，代码改了好几次，也都无法解决

**Comment by c2c3vsfac** [comment]
你这不是原神的吧。
```python
from scapy.all import sniff

def sniff_():
    sniff(count=10, filter="udp port 22102||22101", prn=package_handle)

def package_handle(data):
    print(bytes(data)[:80])

sniff_()
```
改成这样呢，总不能就没输出了吧

**Comment by 2054686334** [comment]
> 你这不是原神的吧。
> 
> ```python
> from scapy.all import sniff
> 
> def sniff_():
>     sniff(count=10, filter="udp port 22102||22101", prn=package_handle)
> 
> def package_handle(data):
>     print(bytes(data)[:80])
> 
> sniff_()
> ```
> 
> 改成这样呢，总不能就没输出了吧

确实不是原神的，全局捕获了我也不知道是什么
更换代码后输出如下
b'\xc8[\xa0\xee&\xc1\x18\xc0M\xda-\xa9\x08\x00E\x00\x000\xdb5\x00\x00\x80\x11\x85\x8b\xc0\xa8{\xbb/tn$\xc8sVU\x00\x1c\xb9\x89\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00I\x96\x02\xd2\xff\xff\xff\xff'
b'\x18\xc0M\xda-\xa9\xc8[\xa0\xee&\xc1\x08\x00E\x00\x000\x01\x97@\x002\x11m*/tn$\xc0\xa8{\xbbVU\xc8s\x00\x1ck$\x00\x00\x01E\x00\x01\xf9\xeaL5\xaegI\x96\x02\xd2\x14QEE'
b'\xc8[\xa0\xee&\xc1\x18\xc0M\xda-\xa9\x08\x00E\x00\x020\xdb6\x00\x00\x80\x11\x83\x8a\xc0\xa8{\xbb/tn$\xc8sVU\x02\x1c5\x90\xea\xf9\x01\x00g\xae5LQ\x00\x00\x01\x98\x9f\xbf\xae\x00\x00\x00\x00\x00\x00\x00\x00\xf8\x01\x00\x00$\x8f\n\x87\xdan\xe1I\x81\xfd'
b'\x18\xc0M\xda-\xa9\xc8[\xa0\xee&\xc1\x08\x00E\x00\x008\x01\xc8@\x002\x11l\xf1/tn$\xc0\xa8{\xbbVU\xc8s\x00$\xd2\x9c\xea\xf9\x01\x00g\xae5LR\x00\x00\x01\x98\x9f\xbf\xae\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00'
b'\x18\xc0M\xda-\xa9\xc8[\xa0\xee&\xc1\x08\x00E\x00\x04/\x01\xce@\x002\x11h\xf4/tn$\xc0\xa8{\xbbVU\xc8s\x04\x1b\xca\xbf\xea\xf9\x01\x00g\xae5LQ\x00\x00\x01\xe3\xa5\xbf\xae\x00\x00\x00\x00\x01\x00\x00\x00\xf7\x03\x00\x00$\x8f\n\xfd\xdal\xe1I\x83\xfe'
b'\xc8[\xa0\xee&\xc1\x18\xc0M\xda-\xa9\x08\x00E\x00\x008\xdb7\x00\x00\x80\x11\x85\x81\xc0\xa8{\xbb/tn$\xc8sVU\x00$\x87\x96\xea\xf9\x01\x00g\xae5LR\x00\x00\x01\xe3\xa5\xbf\xae\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00'
b'\xc8[\xa0\xee&\xc1\x18\xc0M\xda-\xa9\x08\x00E\x00\x03\xa7\xdb8\x00\x00\x80\x11\x82\x11\xc0\xa8{\xbb/tn$\xc8sVU\x03\x93\xdc\x9c\xea\xf9\x01\x00g\xae5LQ\x00\x00\x01\x8c\xa1\xbf\xae\x01\x00\x00\x00\x01\x00\x00\x00o\x03\x00\x00\xc6\x93n\x95\\i\xcd\x98\x96\n'
b'\x18\xc0M\xda-\xa9\xc8[\xa0\xee&\xc1\x08\x00E\x00\x008\x03;@\x002\x11k~/tn$\xc0\xa8{\xbbVU\xc8s\x00$\xdc\x9a\xea\xf9\x01\x00g\xae5LR\x00\x00\x01\x8c\xa1\xbf\xae\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00'
b'\x18\xc0M\xda-\xa9\xc8[\xa0\xee&\xc1\x08\x00E\x00\x02\x1e\x03\x9c@\x002\x11i7/tn$\xc0\xa8{\xbbVU\xc8s\x02\n\xa2\xcb\xea\xf9\x01\x00g\xae5LQ\x00\x00\x01m\xa8\xbf\xae\x01\x00\x00\x00\x02\x00\x00\x00\x15\x00\x00\x00\xc6\x93o\xfe\\k\xcd\x98\x95R'
b'\xc8[\xa0\xee&\xc1\x18\xc0M\xda-\xa9\x08\x00E\x00\x01\x18\xdb9\x00\x00\x80\x11\x84\x9f\xc0\xa8{\xbb/tn$\xc8sVU\x01\x043k\xea\xf9\x01\x00g\xae5LR\x00\x00\x01m\xa8\xbf\xae\x01\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\xea\xf9\x01\x00g\xae5LR\x00'

**Comment by c2c3vsfac** [comment]
那不可能没输出啊，你有自己改了什么部分吗？你试下重新拉代码，然后只把sniff_函数改成这样。
```python
def sniff_():
    sniff(count=0, filter="udp port 22102||22101", prn=package_handle)
```

**Comment by 2054686334** [comment]
> 那不可能没输出啊，你有自己改了什么部分吗？你试下重新拉代码，然后只把sniff_函数改成这样。
> 
> ```python
> def sniff_():
>     sniff(count=0, filter="udp port 22102||22101", prn=package_handle)
> ```

有进展了大佬，输出如下
(base) PS D:\workspace\tmp\Iridium-py-release> python .\iridium-bruteforce.py
send_req_time:1682265641948
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\111\anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\111\anaconda3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "D:\workspace\tmp\Iridium-py-release\iridium-bruteforce.py", line 137, in find_key
    server_seed = rsa_decrypt(server_encrypted_seed)
  File "D:\workspace\tmp\Iridium-py-release\iridium-bruteforce.py", line 172, in rsa_decrypt
    server_private_key = RSA.import_key(rsa_file.read())
AttributeError: module 'Crypto.PublicKey.RSA' has no attribute 'import_key'
应该可以了，我看看什么原因导致的报错，十分感谢

**Comment by 2054686334** [comment]
send_req_time:1682265939502
server_seed:1677321482528970581
please retry
目前输出如下，请问please retry是要我一直尝试登陆吗，尝试好多次了，没有多的输出

**Comment by c2c3vsfac** [comment]
你试着完全退出游戏再重新打开试试，或者如果你网卡的话调大guess_client_key阈值试试

**Comment by 2054686334** [comment]
> 你试着完全退出游戏再重新打开试试，或者如果你网卡的话调大guess_client_key阈值试试

完全退出后输出了，感谢大佬
